- lib/vsc/install/shared_setup.py
- test/licenses.py
- test/setup/PKG-INFO
- test/shared_setup.py
some smart person might actually make this do stuff instead of just print
> Add vsc_release command to show what needs to be done

- lib/vsc/__init__.py
- lib/vsc/fancylogger.py
- lib/vsc/install/__init__.py
- lib/vsc/install/headers.py
- lib/vsc/install/shared_setup.py
- lib/vsc/install/testing.py
Static analysis using [prospector](https://github.com/landscapeio/prospector)
> Prospector static analysis tests

- README.md
- lib/vsc/install/headers.py
- lib/vsc/install/shared_setup.py
- lib/vsc/install/testing.py
> prospector is optional, except on jenkins

- README.md
- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
- lib/vsc/install/testing.py
- test/00-import.py
This is backwards incompatible
> Deprecate VSCImportTest and move it to a dedicated module

- README.md
Fix formatting issues that prevent proper rendering on PyPI
Checks done using readme-renderer Python package, using python setup.py check -rs, cfr. https://gist.github.com/kennethreitz/8378ba05d1a50bea75da
> fix formatting issues in README

- lib/vsc/install/shared_setup.py
fix for #21
I'd love to figure out #16 in this PR, but not sure yet which setuptools to require...
> register 'vsc' as namespace package

- lib/vsc/install/shared_setup.py
- test/shared_setup.py
fixes https://github.com/hpcugent/vsc-base/issues/241
> fix attribute error for uknown attributes in the vsc_setup_klass

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
added a few more lint checks that check things related to our coding styleguides, 
e.g. line too long and use of explicit octal numbers.
just here for reference, can be merged in a while once we feel comfortable doing more cleanup
> more linting

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
This is just a suggestion, but I know I make a lot of these kinds of mistakes.
> add tests for bad whitespace

- Jenkinsfile
- lib/vsc/__init__.py
- lib/vsc/fancylogger.py
- lib/vsc/install/__init__.py
- lib/vsc/install/commontest.py
- lib/vsc/install/headers.py
- lib/vsc/install/shared_setup.py
- lib/vsc/install/testing.py
- test/00-import.py
- test/__init__.py
- test/headers.py
- test/licenses.py
- test/shared_setup.py
- test/testdata/vsc/__init__.py
- test/testdata/vsc/test/__init__.py
- issue with prospector and pylint was fixed in https://github.com/landscapeio/prospector/issues/183
> don't use old pylint anymore to avoid version conflicts

- lib/vsc/install/shared_setup.py
cfr. https://packaging.python.org/specifications/core-metadata/#author-email-optional
> fix format for Author-email field

- .travis.yml
> also use 'tox -c' in Travis CI config

- README.md
- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
@wdpypere required for https://github.ugent.be/hpcugent/icinga-checks/pull/150
> add support for overriding prefix for scripts in vsc-ci.ini when installing vsc-install in tox environment

- lib/vsc/install/shared_setup.py
> Do the splitting of the dependency requirements correctly

- lib/vsc/install/shared_setup.py
- test/shared_setup.py
This should be the final fix for #139 and #140 
One major issue: a split on `>` matches both `>` and `>=`...
> Fix dependency_links injection for real

- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
@wdpypere This is the fix you need for https://github.ugent.be/hpcugent/icinga-checks/pull/153
> also add --install-scripts option to 'pip install' used in Jenkinsfile

- lib/vsc/install/shared_setup.py
@wdpypere as discussed, required for `regice` which still has `setuptools` 0.9.8...
> remove existing .eggs directory for ancient setuptools versions that don't have get_egg_cache_dir method yet in setuptools.dist.Distribution

- lib/vsc/install/shared_setup.py
- test/shared_setup.py
until I can find a way to do it from the depending setup.py
> add psycopg2 to PYTHON_BDIST_RPM_PREFIX_MAP

- lib/vsc/install/shared_setup.py
Some more packages are python 3 only.
Also do not limit the version in case of python 3.
> limit more test dependencies (zipp, configparser)

- lib/vsc/install/shared_setup.py
This should fix all those warnings in python3 about unclosed files. Fixes #157 
@boegel please have a look
> Always close a file handle after read/writing

- lib/vsc/install/shared_setup.py
Fixes error introduced by #160
> small bugfix

- lib/vsc/__init__.py
- lib/vsc/install/__init__.py
- lib/vsc/install/ci.py
- lib/vsc/install/commontest.py
- lib/vsc/install/headers.py
- lib/vsc/install/shared_setup.py
- lib/vsc/install/testing.py
- test/prospectortest.py
- test/prospectortest/lib/vsc/mockinstall/raising_bad_type.py
also clean up some old dependencies. The cleanup works on my machine, looking forward to what Jenkins has to say.
> fix dependencies for platformdirs and pylint-django

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
was removed in https://github.com/hpcugent/vsc-install/pull/219
> restore old pylint hack

- lib/vsc/install/shared_setup.py
> Lock pyyaml down to less than or equal to 6.0.1
