hpcugent/vsc-install

- lib/vsc/install/commontest.py
- lib/vsc/install/headers.py
- lib/vsc/install/shared_setup.py
- test/headers.py
- test/licenses.py
- test/shared_setup.py
- pep8 and pylint are now complaining less
- added a few very interesting errors as failures in prospector: dangerous-default-value and no-value-for-parameter
- moved path detecting code in shared_setup into it's own namespace, so it is rerun when we run shared_setup inside shared_setup (e.g. when installing a package trought python setup.py install, and it's dependencies are also importing the system installed shared_setup, instead of the only current working solution that was installing from pypi with a patched in copy of vsc_install
> cleaned up:

- lib/vsc/install/shared_setup.py
older versions of vsc packages (incl. vsc-base) used something like this in `setup.py`:
```python
import vsc.install.shared_setup as shared_setup
shared_setup.SHARED_TARGET.update({
'url': 'https://github.com/hpcugent/vsc-base',
'download_url': 'https://github.com/hpcugent/vsc-base'
})
```
This got broken by the cleanup in #34, where `SHARED_TARGET` was moved into the `vsc_setup` class.
> fix backward compatibility for SHARED_TARGET constant dict in shared_setup

- lib/vsc/install/shared_setup.py
fix for broken install of vsc-base 2.4.2, caused by changes in #34
```
INFO: This is (based on) vsc.install.shared_setup 0.10.1
Traceback (most recent call last):
File "setup.py", line 69, in <module>
shared_setup.action_target(PACKAGE, urltemplate=URL_GH_HPCUGENT)
TypeError: action_target() got an unexpected keyword argument 'urltemplate'
```
> fix backward compatibility for action_target function in shared_setup

- README.md
- lib/vsc/install/shared_setup.py
- test/shared_setup.py
- test/testdata/vsc/__init__.py
- test/testdata/vsc/test/__init__.py
the excluded pgkgs ware never picked up when we started to cache the package_files, 
so be sure to regenerate the package files with the excluded packages as parameter, once we know it.
> Fix rpm exclude pkgs

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
* the `syntax-error` one is typically caught by our 'import all whatever' tests, but helps to debug such failing test
* unused-import is self-explanatory
> commontest: add more prospector whitelist

- lib/vsc/__init__.py
- lib/vsc/fancylogger.py
- lib/vsc/install/__init__.py
- lib/vsc/install/commontest.py
- lib/vsc/install/headers.py
- lib/vsc/install/shared_setup.py
- lib/vsc/install/testing.py
- test/00-import.py
- test/__init__.py
- test/headers.py
- test/licenses.py
- test/shared_setup.py
for some reason when we manually generate a setup.cfg vsc_install will remove it before a call to bdist_rpm, this doesn't sound all that smart, let's not do that.
> don't cleanup setup.cfg right before creating an rpm

- bin/python-noenv.sh
- bin/python-stripped-env
- lib/vsc/install/headers.py
- lib/vsc/install/shared_setup.py
fix for faulty warning:
```
$ ml swap cluster/golett
$ qsub test.sh 
Unable to determine clustername, using default delcatty (no PBS_DEFAULT)
920763.master19.golett.gent.vsc
```
> add python-stripped-env that can be used as replacement shebang for /usr/bin/python (HPC-6427)

- lib/vsc/install/shared_setup.py
When name was set in PACKAGE vsc-install would not auto detect the url, and not decide if this was a private package and not updating the dependency_links.
This fixes this.
> Always update urls and dependency links, even if name is set

- .travis.yml
This is an easy way to check the `vsc-install` tests against Python 2.6 & 2.7 (and maybe also other Python versions soon, see #83).
We can either rely on both Jenkins & Travis, or just park this `.travis.yml` in the repository and stick to using Jenkins alone (we'll need to tell Travis to run tests before it start interfering with PRs even if a `.travis.yml` is there). Or maybe even we can consider switching to Travis alone and reduce maintenance effort on our private Jenkins instance...
Even if we stick to Jenkins-only this is still useful, since contributors can easily run the tests on Travis rather than running them locally, pretty much with the flick of a switch to enable Travis on their fork only (like I did, see https://travis-ci.org/boegel/vsc-install).
That way they can check …
> add Travis config

- lib/vsc/install/shared_setup.py
fix pylint and pyflakes to older version
> Pylintfix:  depedencies break in new pylint and pyflakes

- lib/vsc/install/shared_setup.py
cfr. https://github.com/hpcugent/vsc-install/pull/90/files#r231935729
> drop useless lines to constrict pylint version requirement with Python 2.x

- lib/vsc/install/shared_setup.py
(fixes #94)
With old `setuptools` versions, `klass.SHARED_TARGET['cmdclass']` happens to be a *reference* to `self.cmdclass`, so changing that also changes `self.cmdclass`.
This is no longer the case in recent `setuptools` versions however, because the arguments passed to the `setup` function are being copied into a new dictionary: see https://github.com/pypa/setuptools/blob/v38.4.0/setuptools/__init__.py#L113.
Hence, `klass.SHARED_TARGET['cmdclass']` is no longer a reference to `self.cmdclass`, and any changes made to it have no effect whatsoever since `SHARED_TARGET` is only used in `parse_target`, which is used to construct the arguments for the call to the `setup` function.
This basically worked by accident I think, doesn't look like we were intentionally avoiding to use …
> tweak egg_info & sdist directly in self.cmdclass in vsc_bdist_rpm.run (HPC-7552)

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
I was bitten by this in a script with nasty side effects. Can we enable this?
to prevent following example like functions returning None:
```
def test:
if something:
return integer
```
> add "inconsistent-return-statements" to the whitelist

- lib/vsc/install/shared_setup.py
- test/shared_setup.py
general fix that replaces https://github.com/hpcugent/vsc-mympirun/pull/154
> specify long_description_content_type based on extension of README file

- bin/python-stripped-env
- lib/vsc/install/shared_setup.py
We had a user that had:
```bash
export GREP_OPTIONS='--color=always'
```
in his `.bash_profile` and it breaks python-stripped-env.
> Make sure that grep never uses colors

- bin/python-noenv.sh
- bin/python-stripped-env
- lib/vsc/install/shared_setup.py
Things in `~/.local/lib/python2.7/` still get picked up by `python-stripped-env`
It seems like python 3 has something even better: `-I`.
> Ignore user site directory in python-stripped-env

- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
- tox.ini
fix for:
```
Traceback (most recent call last):
File "/var/lib/jenkins/jobs/hpc ugent github.com/jobs/vsc-config/branches/PR-98/workspace/test/env.py", line 170, in setUp
self.orig_user = os.environ['USER']
File "/var/lib/jenkins/jobs/hpc ugent github.com/jobs/vsc-config/branches/PR-98/workspace/.tox/py27/lib/python2.7/UserDict.py", line 23, in __getitem__
raise KeyError(key)
KeyError: 'USER'
```
> configure tox to pass down $USER into virtualenv used to run tests

- lib/vsc/install/ci.py
- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
- test/ci.py
- tox.ini
`setuptools` 42.0 has changed the `easy_install` function to use `pip` if it's available, which breaks some assumptions currently made by `vsc-install`, primarily that failing installations using the URLs in `dependency_links` are safe to ignore
> setuptools < 42.0 is required for now [HPC-7603]

- lib/vsc/install/shared_setup.py
- lib/vsc/install/testing.py
- test/testing.py
Tests for `vsc.install.testing` were still located in `vsc-base` after move from `vsc.utils.testing`, but they belong here.
Some tests in `vsc-base` are failing with Python 3 because of the issues fixed here.
> add tests for vsc.install.testing (taken from vsc-base) + fix issues with Python 3

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
In places where we use `reduce` (built-in in Python 2, but not in Python 3), we need to use:
```
from functools import reduce
```
to make the code compatible with Python 3.
To avoid that `prospector` bitches about redefining the `reduce` builtin when the tests are run with Python 2, we need to blacklist the corresponding message...
The "redefinition" of `reduce` is a false positive in Python 2 btw:
```
>>> type(reduce)
<type 'builtin_function_or_method'>
>>> from functools import reduce
>>> type(reduce)
<type 'builtin_function_or_method'>
>>>
```
> allow redefining of 'reduce' builtin by blacklisting corresponding prospector message

- Jenkinsfile
- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
Jenkins doesn't re-create a clean checkout when it's re-running the tests for an existing PR (for example when a commit was added).
This can cause problems if `*.py` files were removed for some reason, since the corresponding `*.pyc` files will remain in place.
Fixed by running `git clean -fxd` after checkout, which was already present in some `Jenkinsfile`s (but it wasn't clear why, now it is).
Example of a failing test suite run without the `git clean`: https://github.com/hpcugent/jobcli/pull/76#issuecomment-571939211
> also run 'git clean -fxd' in Jenkinsfile to remove untracked files

- README.md
- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
fixes #131 (see also https://github.ugent.be/hpcugent/quattor-host-mngmt-tools/pull/11)
> add support for opting in to also running shellcheck in generated Jenkinsfile

- lib/vsc/install/shared_setup.py
Inject dependency links with expliciet version is only useful when `==`,
`>=` or `<=` is used. If there is not a `=`, the dependency links is
pointless.
> Only inject dependency version when a equal is allowed

- Jenkinsfile
- README.md
- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
- tox.ini
- vsc-ci.ini
(marked WIP because tests will currently fail on Jenkins because there is no Python 3.6 available yet there, will be fixed in new Jenkins setup...)
> add support for specifying in vsc-ci.ini that tests must pass using Python 3 (and use it for vsc-install) (HPC-7603)

- lib/vsc/install/shared_setup.py
When private repositories (like `vsc-config`) are being tested through `tox`, dependencies that are located in a public repo (for example `vsc-base` as a dep for `vsc-config`) should be cloned over `https` rather than `ssh` to avoid that the `git clone` command requires credentials (see #124).
> consider git+https:// before git+ssh:// URLs for dependencies

- test/shared_setup.py
Doesn't require a version bump, since it's only in the tests, and doesn't change anything functionally...
> stop using deprecated assertEquals, use assertEqual instead

- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
required for `vsc-jobs`, where we need to inherit PySlurm from the OS (see https://github.com/hpcugent/vsc-jobs/pull/152)
> add support for installing tox with 'pip install' and for including ' sitepackages = true' in tox.ini

- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
`shellcheck` downloaded from `storage.googleapis.com` URL fails with:
```
+ ./shellcheck --version
You are downloading ShellCheck from the wrong URL!
Please update to the latest one:
https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz
For more information, see:
https://github.com/koalaman/shellcheck/issues/1871
```
See also https://github.com/koalaman/shellcheck/issues/1871
> use correct URL for shellcheck

- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
- tox.ini
This is required to avoid mixing Python packages installed with Python 2 & 3, which can lead to issues like:
```
(shellcmd ['/var/lib/jenkins/jobs/hpcugent_github.ugent/jobs/vsc-burstbuffer/branches/PR-17/workspace/.tox/py36/bin/python', '-c', 'import vsc.burstbuffer; print(vsc.burstbuffer.__file__)']) output Failed to import the site module
Error processing line 1 of /var/lib/jenkins/jobs/hpcugent_github.ugent/jobs/vsc-burstbuffer/branches/PR-17/workspace/.tox/py36/lib/python3.6/site-packages/_virtualenv.pth:
Traceback (most recent call last):
File "/usr/lib64/python3.6/site.py", line 168, in addpackage
exec(line)
File "<string>", line 1, in <module>
File "/var/lib/jenkins/jobs/hpcugent_github.ugent/jobs/vsc-burstbuffer/branches/PR-17/workspace/.tox/py36/lib/python3.6/site-packages/_virtu …
```
> clean up .eggs directory in tox.ini before running tests

- .gitignore
- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
- tox.ini
If this approach is better, I can also roll back the changes done in #150 in this PR, since they're not needed anymore...
It will still require to update `.gitignore` everywhere though, to add `.eggs.py2` and `.eggs.py3`.
> use .eggs.py2 or .eggs.py3, depending on Python version being used

- lib/vsc/install/shared_setup.py
Repository `https` URLs do not necessarily end in `.git`. For instance, `git clone https://github.com/hpcugent/vsc-install` works and the remote will be registered without `.git`.
> make .git extension optional for repository URL

- Jenkinsfile
- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
This is done to avoid that the tests run for different repositories step on each others toes on `jenkins10`, by not using a shared tox installation in `$HOME/.local`...
> don't install tox with --user in Jenkinsfile, use --prefix instead

- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
The `--install-scripts` option is only needed to override the one specified in `setup.cfg`, but the `pip install` commands in `Jenkinsfile` in repos where this is an issue are run from `$HOME` to ignore the `setup.cfg`
Using `--install-option` when installing `tox` in `Jenkinsfile` causes problems, because it trigers `pip` to not download pre-built wheels from PyPI:
```
UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options
```
The side effect of this is that `tox` dependencies like `virtualenv` need to be installed from source, which results in problems like:
```
setuptools >= 41 required to build
```
This is basically a bug in `vsc-install`, there's no point in passing the `--install-scripts` option when installing `tox` in …
> --install-scripts install option should only be used in tox.ini, not in Jenkinsfile

- lib/vsc/install/shared_setup.py
This PR makes it easier to update the allowed git remotes in `vsc-install`. It does not change current behaviour.
> Add global with allowed remotes

- lib/vsc/__init__.py
- lib/vsc/install/__init__.py
- lib/vsc/install/ci.py
- lib/vsc/install/commontest.py
- lib/vsc/install/headers.py
- lib/vsc/install/shared_setup.py
- lib/vsc/install/testing.py
- test/00-import.py
- test/__init__.py
- test/ci.py
- test/commontest.py
- test/headers.py
- test/licenses.py
- test/prospectortest.py
- test/shared_setup.py
- test/testdata/vsc/__init__.py
- test/testdata/vsc/test/__init__.py
- test/testing.py
we have started adding restrictions to the requirements to work around limitations of pypi (specifically when certain dependencies are only supported for more recent python versions). however, we now have run into issues where these restrictions cause probems when making rpms while the too recent version issue does not exist in such an environment
> manipulate dependencies for rpm building

- lib/vsc/install/ci.py
- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
I was cleaning up some code and I think its time to enable `logging-not-lazy`, the other 2 `no-member` and `logging-too-few-args` are needed to show bugs I encountered when cleaning up things.
> give errors about logging-not-lazy

- README.md
- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
also sorted those lines for easier reading, and removed duplicates. also add 'c-extension-no-member' to the blacklist.
> update examples and add logging-too-many-args

- lib/vsc/install/shared_setup.py
when you run tox  it creates a `bin/__pycache__` directory. If you run `python setupy.py install --user` afterwards vsc-install refuses to install because the directory is there.
```
INFO: installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
INFO: running install_scripts
INFO: running build_scripts
INFO: creating build/scripts-3.9
error: [Errno 21] Is a directory: 'bin/__pycache__'
```
So I believe it should be ignored on install.
> exclude bin/__pycache__ when doing local install

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
fail on code like:
```
self.output_clients(total_clients, total_sources);
```
> enable pylint unnecessary-semicolon

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
this warns on possible logical issues like:
```
def function_without_return():                                                                                                                               
x = 1 + 1                                                                                                                                                
print(x)                                                                                                                                                 
y = function_without_return()  
```
```
E1111: Assigning result of a function call, where the function has no return (assignment-from-no-return)
```
this is correct syntax, but is probably never what you want.
> enable pylint assignment-from-no-return

- lib/vsc/install/headers.py
- lib/vsc/install/shared_setup.py
- test/headers.py
- test/setup/git_config_6
- test/shared_setup.py
The old name 'sisc-hpc' is no longer relevant.
> New name for VUB gh organization: vub-hpc

- lib/vsc/install/shared_setup.py
We are transitioning our private repos to Azure and some of them rely on vsc-install. This PR adds our `dev.azure.com` domain to `GIT_REMOTES`.
> add dev.azure.com/VUB-ICT to the list of allowed GIT remotes

- lib/vsc/install/shared_setup.py
https://github.com/hpcugent/vsc-install/pull/190 broke our internal testing. it did not take into account local githubs.
> re-add support for internal githubs

- lib/vsc/install/headers.py
- lib/vsc/install/shared_setup.py
Now that we can work with our non-github repos, we had a few test failures. 
* I'm changing our `institute_details` to just be VUB so it work for both our github and azure repos
* also setting a `download_url` to None for any non-github repo
> fix tests for non-github repos

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
- test/prospectortest/lib/vsc/mockinstall/bad_whitespace.py
required to fix problem when running tests (for example for `vsc-config` in #155
```
pkg_resources.ContextualVersionConflict: (pyflakes 2.3.1 (/var/lib/jenkins/jobs/hpcugent_github.com/jobs/vsc-config/branches/PR-155/workspace/.eggs.py3/pyflakes-2.3.1-py3.6.egg), Requirement.parse('pyflakes<2.3.0,>=2.2.0'), {'flake8'})
```
> remove restriction on flake8, both flake8 and prospector now require pyflakes < 2.4.0

- lib/vsc/install/shared_setup.py
The `~=` means "compatible release", see https://www.python.org/dev/peps/pep-0440/#compatible-release
This will hopefully save us for a while for the version conflicts that keep popping up for *every* Python package we have due to new releases for (transitive) dependencies of `prospector` & co...
> fix dep hell for astroid/pylint/flake8/prospector by fixing major/minor versions

- lib/vsc/install/shared_setup.py
see https://github.com/ionelmc/python-lazy-object-proxy/issues/61
> lock lazy_object_proxy to < 1.7.0 for python2

- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
as I'm preparing new test hosts that don't have python2.7 available anymore, I don't think this test should still be there on python3 only projects.
e.g. remove the following line from stage 'test':
```
stage('test') {
sh 'python2.7 -V'
}
```
> don't test for python2 on py3 only projects

- .github/workflows/unittest.yml
avoid the deprecation warnings on nodejs 12.
> update gh action versions

- Jenkinsfile
- README.md
- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
- test/shared_setup.py
- tox.ini
- vsc-ci.ini
this is a first nudge in the direction of removing python2 support. it makes py3_only mandatory. it will try to give warnings and errors about python2, but I'm actually quite sure it just won't work.
Should not be merged before all known packages have been migrated.
> start removing python 2 support

- lib/vsc/install/ci.py
- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
- lib/vsc/install/testing.py
- test/ci.py
- vsc-ci.ini
- remove old hack which depends on deprecated optparse
- remove some more python 2 related dependency handling
- explain distutils.log usage a bit better
- get rid of `is_string()` function
- deprecate and ignore py3_only and py3_tests options, so they are no longer mandatory, and can safely be removed
> more general cleanup

- lib/vsc/install/shared_setup.py
This cause an error in github pipelines. The logger class needs to have
a doc string...
See https://github.com/wpoely86/vsc-accountpage/actions/runs/4821249134/jobs/8586871529
> Fix error in case of installing with pip and pyproject.toml

- .github/workflows/unittest.yml
- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
We hit issue https://github.com/pypa/virtualenv/issues/2550 due to changes from https://github.com/pypa/virtualenv/pull/2548 . This means that all tests in Python 3.6 fail with latest versions of `tox` and `virtualenv`.
This PR caps the versions to those still compatible with Python 3.6.
> pin versions of virtualenv and tox compatible with Python v3.6

- lib/vsc/install/shared_setup.py
this works. I'll make an attempt at making the versions a bit newer, but it's dependency hell between prospector and pylint-django.
whoever said it tested and worked on py3.11 was surely wrong. (probably me)
> add a workable test stack for python 3.9

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
While doing some cleanup I found that we have some small issues we could check for:
`consider-using-dict-comprehension`,  `consider-using-set-comprehension`: both mostly leftover from python2 times, as they are less readably and use a transient list they are slower, I propose to fix those. (see https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-set-comprehension.html and https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-dict-comprehension.html)
`implicit-str-concat`: I found 2 instances of this, and both were typos which were unwanted behaviour. (https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/implicit-str-concat.html)
> add 3 pylint issues to check for

- lib/vsc/install/commontest.py
- lib/vsc/install/shared_setup.py
These are the main pylint tests which flag "old school" coding style from before python 3.6.
- I'm a bit hesitant to enable `consider-using-fstring` because it's a lot. I cleaned out a lot of projects already but still.
- `super-with-arguments`: was for python 2
- `useless-object-inheritance`: same, no need to add it anymore
- `unidiomatic-typecheck`: use `isinstance(var, type)` instead of `if type(var) == type`
- `unnecessary-pass`: if an  empty function or class has a docstring, a `pass` is not needed.
This PR will fail it's own tests, needs https://github.com/hpcugent/vsc-install/pull/234
opinions?
> enable more pylint

- lib/vsc/install/ci.py
- lib/vsc/install/shared_setup.py
- test/ci.py
we don't notice this because we have set it to true in all `vsc-ci.ini` files. but it really should be default.
> python 3.9 tests must pass by default

- lib/vsc/install/shared_setup.py
Mock is part of the standard library of Python since 3.3. This library was a backport of the mock of newer Python. But the package is in a almost sleep state with little activity. It was also dropped from EPEL as unmaintained. 
I wouldn't know why we still need it. We don't use any features of mock which are not yet present in the mock of Python 3.9?
> drop mock requirement
